### ISSUE TITLE
Couldn't set locale czy

### ISSUE THREAD

**Issue by pschonmann** [hsoft/moneyguru#394]
Seems moneyguru have problem to set proper locale, expecting that "czy" should be "csy"

<pre>
2014-04-14 21:36:12,214 - WARNING - Couldn't set locale czy
2014-04-14 21:38:28,048 - WARNING - Traceback (most recent call last):
2014-04-14 21:38:28,048 - WARNING -   File "C:\Python33\lib\logging\__init__.py", line 939, in emit
2014-04-14 21:38:28,049 - WARNING -   File "C:\Python\64-bit\3.3\lib\encodings\cp1250.py", line 19, in encode
2014-04-14 21:38:28,049 - WARNING - UnicodeEncodeError: 'charmap' codec can't encode character '\xe8' in position 45: character maps to <undefined>
2014-04-14 21:38:28,049 - WARNING - Logged from file __init__.py, line 1773
2014-05-03 01:10:23,563 - WARNING - Couldn't set locale czy
2014-05-13 12:14:20,478 - WARNING - Couldn't set locale czy
2014-05-13 12:16:44,233 - WARNING - Couldn't set locale czy
2014-07-20 15:21:42,136 - WARNING - Couldn't set locale czy
2014-07-20 15:21:51,441 - WARNING - Couldn't set locale czy
2014-07-20 15:28:51,856 - WARNING - Couldn't set locale czy
2014-07-20 15:39:32,033 - WARNING - Traceback (most recent call last):
2014-07-20 15:39:32,033 - WARNING -   File "C:\Python33\lib\logging\__init__.py", line 939, in emit
2014-07-20 15:39:32,033 - WARNING -   File "C:\Python\64-bit\3.3\lib\encodings\cp1250.py", line 19, in encode
2014-07-20 15:39:32,033 - WARNING - UnicodeEncodeError: 'charmap' codec can't encode character '\xe8' in position 45: character maps to <undefined>
2014-07-20 15:39:32,034 - WARNING - Logged from file __init__.py, line 1773
2014-07-20 22:08:32,262 - WARNING - Couldn't set locale czy
2014-07-20 22:15:40,166 - WARNING - Couldn't set locale czy
2014-07-21 22:35:45,498 - WARNING - Couldn't set locale czy
2014-07-21 22:35:55,766 - WARNING - Communication problem with currency.hardcoded.net: [Errno 11004] getaddrinfo failed
2014-07-21 22:54:34,910 - WARNING - Couldn't set locale czy
</pre>

**Comment by hsoft** [comment]
Because this issue is windows-specific and that [I don't touch Windows anymore](https://www.hardcoded.net/archive2015#2015-11-01), this ticket is on hold.

After the feature release coming after 2.10, I'll start stripping Windows support from the code itself (unless, of course, someone steps up to take maintain the Windows part of moneyGuru), at which time this issue will become irrelevant.
