### ISSUE TITLE
Error importing QFX file (2.9)

### ISSUE THREAD

**Issue by ddhawk** [hsoft/moneyguru#432]
Just upgraded to 2.9, had this error for the first time. Happens after choosing QFX file for Import. Import doesn't execute. Tried other QFX files that had previously imported OK in previous versions, got same error. 

Traceback:

```
Application Identifier: com.hardcoded-software.moneyguru
Application Version: 2.9.0
Mac OS X Version: Version 10.10.4 (Build 14E46)

Traceback (most recent call last):
  File "/Applications/moneyGuru.app/Contents/Resources/mg_cocoa.py", line 1105, in import_
    self.model.parse_file_for_import(filename)
  File "build/moneyGuru.app/Contents/Resources/py/core/gui/main_window.py", line 481, in parse_file_for_import
  File "build/moneyGuru.app/Contents/Resources/py/core/gui/main_window.py", line 384, in load_parsed_file_for_import
  File "build/moneyGuru.app/Contents/Resources/py/core/gui/import_window.py", line 640, in show
  File "build/moneyGuru.app/Contents/Resources/py/core/gui/import_window.py", line 631, in refresh_panes
  File "build/moneyGuru.app/Contents/Resources/py/core/gui/import_window.py", line 64, in __init__
  File "build/moneyGuru.app/Contents/Resources/py/core/gui/import_window.py", line 242, in match_entries
  File "build/moneyGuru.app/Contents/Resources/py/core/gui/import_window.py", line 85, in _determine_best_matches
  File "build/moneyGuru.app/Contents/Resources/py/core/gui/import_window.py", line 77, in check_better
AttributeError: 'EntryProbability' object has no attribute 'probability'
```

**Comment by hsoft** [comment]
Thanks for the report. It's probably a regression, will fix soon.

**Comment by manuch54** [comment]
Looks like I've got the same on Fedora 22 x64. Here is the error :

Application Name: moneyGuru
Version: 2.9.0

Traceback (most recent call last):
  File "/usr/share/moneyguru/qt/controller/main_window.py", line 628, in importDocument
    self.model.parse_file_for_import(docpath)
  File "/usr/share/moneyguru/core/gui/main_window.py", line 481, in parse_file_for_import
    self.load_parsed_file_for_import()
  File "/usr/share/moneyguru/core/gui/main_window.py", line 384, in load_parsed_file_for_import
    self.import_window.show()
  File "/usr/share/moneyguru/core/gui/import_window.py", line 640, in show
    self.refresh_panes()
  File "/usr/share/moneyguru/core/gui/import_window.py", line 631, in refresh_panes
    target_account))
  File "/usr/share/moneyguru/core/gui/import_window.py", line 64, in __init__
    self.match_entries()
  File "/usr/share/moneyguru/core/gui/import_window.py", line 242, in match_entries
    self._determine_best_matches(matches)
  File "/usr/share/moneyguru/core/gui/import_window.py", line 85, in _determine_best_matches
    check_better(imported_entry, weight)
  File "/usr/share/moneyguru/core/gui/import_window.py", line 77, in check_better
    if conflict and conflict.probability < weight:
AttributeError: 'EntryProbability' object has no attribute 'probability'

**Comment by brownnrl** [comment]
Sorry I am on the road otherwise I'd make an attempt.  If I recall, this center's around the object (which should I think be called an EntryMatch) which kept some bookkeeping info on the best match.  The attribute was called a probability, but the name was changed to weight instead since it wasn't really a probability in the strict measured sense.  Don't know how that would sneak past tests.  Sorry.

**Comment by hsoft** [comment]
@brownnrl it passed the test because the reference bind shipped in core plugins doesn't do any fuzzy matching. I had to introduce a dummy test bind plugin to reach that code.

**Comment by hsoft** [comment]
@ddhawk @manuch54 moneyGuru 2.9.1 is out. Could you try it and confirm that your import now works properly?

**Comment by ddhawk** [comment]
Virgil,

Yes, 2.9.1 resolves the error. Thanks.

dave
