### ISSUE TITLE
First run crash

### ISSUE THREAD

**Issue by wtatbu** [hsoft/moneyguru#437]
moneyGuru will crash with the error report below if the directory ~/Library/Application Support/moneyGuru does not already exist.  Creating this directory allows it to start normally.

Application Identifier: com.hardcoded-software.moneyguru
Application Version: 2.9.2
Mac OS X Version: Version 10.9.5 (Build 13F1096)

Traceback (most recent call last):
  File "/Applications/moneyGuru.app/Contents/Resources/mg_cocoa.py", line 66, in __init__
    appdata_path=appdata_path)
  File "build/moneyGuru.app/Contents/Resources/py/core/app.py", line 173, in __init__
  File "build/moneyGuru.app/Contents/Resources/py/core/app.py", line 220, in _load_user_plugins
FileNotFoundError: [Errno 2] No such file or directory: '/Users/shillas/Library/Application Support/moneyGuru/moneyguru_plugins'

**Comment by hsoft** [comment]
Oh, that's embarassing. It crashes when trying to create the plugins folder because the parent folder doesn't exist. This bug doesn't happen under Qt because we already create the parent folder earlier to host the debug log.
