### ISSUE TITLE
MoneyGuru crashed exporting to QIF

### ISSUE THREAD

**Issue by thenaterhood** [hsoft/moneyguru#460]
Application Name: moneyGuru
Version: 2.10.0

Traceback (most recent call last):
  File "/usr/share/moneyguru/qt/controller/export_panel.py", line 106, in exportButtonClicked
    self.accept()
  File "/usr/share/moneyguru/qt/controller/panel.py", line 93, in accept
    self.model.save()
  File "/usr/share/moneyguru/core/gui/base.py", line 328, in save
    self._save()
  File "/usr/share/moneyguru/core/gui/export_panel.py", line 46, in _save
    save_func(self.export_path, accounts, daterange=daterange)
  File "/usr/share/moneyguru/core/saver/qif.py", line 53, in save
    fd = open(filename, 'wt', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: "('/home/nate/export.qif', 'QIF Files (*.qif)')"

**Comment by thenaterhood** [comment]
...and CSV, with the same error:

Application Name: moneyGuru
Version: 2.10.0

Traceback (most recent call last):
  File "/usr/share/moneyguru/qt/controller/export_panel.py", line 106, in exportButtonClicked
    self.accept()
  File "/usr/share/moneyguru/qt/controller/panel.py", line 93, in accept
    self.model.save()
  File "/usr/share/moneyguru/core/gui/base.py", line 328, in save
    self._save()
  File "/usr/share/moneyguru/core/gui/export_panel.py", line 46, in _save
    save_func(self.export_path, accounts, daterange=daterange)
  File "/usr/share/moneyguru/core/saver/csv.py", line 15, in save
    fp = open(filename, 'wt', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: "('/home/nate/export.csv', 'CSV Files (*.csv)')"

**Comment by thenaterhood** [comment]
Stand by, I'll have a pull in a couple minutes.

**Comment by hsoft** [comment]
Good catch (I never export my stuff, so I don't catch those). That one is due to the qt5 transition.
