### ISSUE TITLE
AttributeError: 'TotalRow' object has no attribute 'entry'

### ISSUE THREAD

**Issue by thenaterhood** [hsoft/moneyguru#483]
Unfortunately, I'm not sure how I triggered this.

Application Name: moneyGuru
Version: 2.10.2

Traceback (most recent call last):
  File "/usr/share/moneyguru/qt/support/item_view.py", line 156, in mousePressEvent
    self._handleMousePressEvent(event, QTableView.mousePressEvent)
  File "/usr/share/moneyguru/qt/support/item_view.py", line 127, in _handleMousePressEvent
    if delegate.handleClick(index, relativePos, rect, selected):
  File "/usr/share/moneyguru/qt/support/item_delegate.py", line 100, in handleClick
    dec.onClickCallable(index)
  File "/usr/share/moneyguru/qt/controller/account/table.py", line 26, in show_transfer_account
    self._model.show_transfer_account(row_index=index.row())
  File "/usr/share/moneyguru/core/gui/entry_table.py", line 108, in show_transfer_account
    entry = self[row_index].entry
AttributeError: 'TotalRow' object has no attribute 'entry'

**Comment by Arvnd** [comment]
Yes. seems to be related to #484

**Comment by hsoft** [comment]
#489 has a bit of context that might help reproduce the issue.
