### ISSUE TITLE
When when Clicking on Arrow for transaction

### ISSUE THREAD

**Issue by Arvnd** [hsoft/moneyguru#484]
This error seems to arise when I click on the arrow point to transactions after import.

Application Name: moneyGuru
Version: 2.9.4

Traceback (most recent call last):
  File "C:\src\moneyguru\qt\support\item_view.py", line 156, in mousePressEvent
  File "C:\src\moneyguru\qt\support\item_view.py", line 127, in _handleMousePressEvent
  File "C:\src\moneyguru\qt\support\item_delegate.py", line 100, in handleClick
  File "C:\src\moneyguru\qt\controller\transaction\table.py", line 32, in show_to_account
  File "C:\src\moneyguru\core\gui\transaction_table.py", line 91, in show_to_account
  File "C:\src\moneyguru\core\gui\transaction_table.py", line 75, in _show_account
AttributeError: 'TotalRow' object has no attribute 'transaction'

**Comment by wolfpackmars2** [comment]
Possibly related #483

**Comment by Arvnd** [comment]
Yes. seems to be related

**Comment by hsoft** [comment]
Closing because it's a duplicate
