### ISSUE TITLE
AttributeError: 'TotalRow' object has no attribute 'entry'  - bug

### ISSUE THREAD

**Issue by GiovanniMoretti** [hsoft/moneyguru#489]
I've just imported some transactions and was on the tab showing all transaction in the account, and clicked on the arrow icon in the 'Transfer' column in the last 'TOTAL' row, and this error appears:

Traceback (most recent call last):
  File "/usr/share/moneyguru/qt/support/item_view.py", line 156, in mousePressEvent
    self._handleMousePressEvent(event, QTableView.mousePressEvent)
  File "/usr/share/moneyguru/qt/support/item_view.py", line 127, in _handleMousePressEvent
    if delegate.handleClick(index, relativePos, rect, selected):
  File "/usr/share/moneyguru/qt/support/item_delegate.py", line 100, in handleClick
    dec.onClickCallable(index)
  File "/usr/share/moneyguru/qt/controller/account/table.py", line 26, in show_transfer_account
    self._model.show_transfer_account(row_index=index.row())
  File "/usr/share/moneyguru/core/gui/entry_table.py", line 108, in show_transfer_account
    entry = self[row_index].entry
AttributeError: 'TotalRow' object has no attribute 'entry'

**Comment by hsoft** [comment]
This is a duplicate to #483, which is why I'll be closing this issue, but thanks for the context around the crash, it might help to reproduce the issue reliably.
