### ISSUE TITLE
Stacktrace on open example document (2.13.1)

### ISSUE THREAD

**Issue by brownnrl** [hsoft/moneyguru#505]
I had another stack trace on opening a different document.  I didn't capture the stack trace reported at the time, so I tried opening up a sample document, and this stack occurred.  I think I saw in the commits that you were removing example documents, so I don't know how much time this is worth investing.  But I've seen this error arise on importing transactions and I think it was similar to a stack trace I encountered on opening a new document.

```
Application Name: moneyGuru
Version: 2.13.1

TypeError: unorderable types: _ccore.Transaction() < _ccore.Transaction()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nelson/projects/moneyguru/qt/controller/document.py", line 96, in openExampleDocument
    self.model.adjust_example_file()
  File "/home/nelson/projects/moneyguru/core/document.py", line 1176, in adjust_example_file
    self._cook()
  File "/home/nelson/projects/moneyguru/core/document.py", line 483, in _cook
    self.oven.cook(from_date=from_date, until_date=self.date_range.end)
  File "/home/nelson/projects/moneyguru/core/model/oven.py", line 88, in cook
    self._transactions.sort() # needed in case until_date is None
SystemError: <built-in method sort of TransactionList object at 0x7fa27cca1548> returned a result with an error set
```

**Comment by hsoft** [comment]
Yeah, the example document is broken, I should have removed it from 2.13 but forgot.

Exception on new document or importing isn't normal though. Was the stack trace really about unorderable types for import too?

**Comment by brownnrl** [comment]
I'm not sure, I didn't copy the stack trace at that moment, and I had trouble replicating the error.  I'm going to attempt a few different variations and see if I can get something repeatable.  How do you normally configure logging?  I started to look through that again. 
 Through the conf.json file?

**Comment by hsoft** [comment]
There used to be debug logging configuration, but it seemed redundant with stdout redirection. To run moneyGuru in debug mode, you run `moneyguru --debug` and redirect stdout if you want.
