### ISSUE TITLE
Crash when adding new item, then changing amount on account

### ISSUE THREAD

**Issue by nruri** [hsoft/moneyguru#514]
Application Name: moneyGuru
Version: 3.0.0

Traceback (most recent call last):
  File "/home/x/hsoft/moneyguru/qt/controller/table.py", line 186, in submit
    self.model.save_edits()
  File "/home/x/hsoft/moneyguru/core/gui/transaction_table_base.py", line 108, in save_edits
    super().save_edits()
  File "/home/x/hsoft/moneyguru/core/gui/table.py", line 412, in save_edits
    row.save()
  File "/home/x/hsoft/moneyguru/core/gui/entry_table_base.py", line 213, in save
    self.table.mainwindow.revalidate()
  File "/home/x/hsoft/moneyguru/core/gui/base.py", line 200, in revalidate
    self._revalidate()
  File "/home/x/hsoft/moneyguru/core/gui/main_window.py", line 309, in _revalidate
    self._current_pane.view.revalidate()
  File "/home/x/hsoft/moneyguru/core/gui/base.py", line 200, in revalidate
    self._revalidate()
  File "/home/x/hsoft/moneyguru/core/gui/account_view.py", line 46, in _revalidate
    TransactionViewBase._revalidate(self)
  File "/home/x/hsoft/moneyguru/core/gui/transaction_view.py", line 45, in _revalidate
    self.table.refresh_and_show_selection()
  File "/home/x/hsoft/moneyguru/core/gui/table.py", line 585, in refresh_and_show_selection
    self.refresh(refresh_view=False)
  File "/home/x/hsoft/moneyguru/core/gui/table.py", line 393, in refresh
    self._fill()
  File "/home/x/hsoft/moneyguru/core/gui/entry_table.py", line 77, in _fill
    rows = self._get_account_rows(account)
  File "/home/x/hsoft/moneyguru/core/gui/entry_table_base.py", line 389, in _get_account_rows
    row = self.ENTRY_ROWCLASS(self, entry, account)
  File "/home/x/hsoft/moneyguru/core/gui/entry_table_base.py", line 149, in __init__
    self.load()
  File "/home/x/hsoft/moneyguru/core/gui/entry_table_base.py", line 197, in load
    self._load_from_fields(entry, self.FIELDS)
  File "/home/x/hsoft/moneyguru/core/gui/table.py", line 673, in _load_from_fields
    setattr(self, row_attr, getattr(target, target_attr))
ValueError: year 4440835 is out of range

The crash happens on an account with a few scheduled transactions setup.
I tested on another account without scheduled transactions and it doesn't crash.

**Comment by nruri** [comment]
Just want to add to the above issue. I get a crash when I try to add a reconcile date to any entry on this account.

Application Name: moneyGuru
Version: 3.0.0

Traceback (most recent call last):
  File "/home/x/hsoft/moneyguru/qt/controller/table.py", line 186, in submit
    self.model.save_edits()
  File "/home/x/hsoft/moneyguru/core/gui/transaction_table_base.py", line 108, in save_edits
    super().save_edits()
  File "/home/x/hsoft/moneyguru/core/gui/table.py", line 412, in save_edits
    row.save()
  File "/home/x/hsoft/moneyguru/core/gui/entry_table_base.py", line 213, in save
    self.table.mainwindow.revalidate()
  File "/home/x/hsoft/moneyguru/core/gui/base.py", line 200, in revalidate
    self._revalidate()
  File "/home/x/hsoft/moneyguru/core/gui/main_window.py", line 309, in _revalidate
    self._current_pane.view.revalidate()
  File "/home/x/hsoft/moneyguru/core/gui/base.py", line 200, in revalidate
    self._revalidate()
  File "/home/x/hsoft/moneyguru/core/gui/account_view.py", line 46, in _revalidate
    TransactionViewBase._revalidate(self)
  File "/home/x/hsoft/moneyguru/core/gui/transaction_view.py", line 45, in _revalidate
    self.table.refresh_and_show_selection()
  File "/home/x/hsoft/moneyguru/core/gui/table.py", line 585, in refresh_and_show_selection
    self.refresh(refresh_view=False)
  File "/home/x/hsoft/moneyguru/core/gui/table.py", line 393, in refresh
    self._fill()
  File "/home/x/hsoft/moneyguru/core/gui/entry_table.py", line 77, in _fill
    rows = self._get_account_rows(account)
  File "/home/x/hsoft/moneyguru/core/gui/entry_table_base.py", line 389, in _get_account_rows
    row = self.ENTRY_ROWCLASS(self, entry, account)
  File "/home/x/hsoft/moneyguru/core/gui/entry_table_base.py", line 149, in __init__
    self.load()
  File "/home/x/hsoft/moneyguru/core/gui/entry_table_base.py", line 197, in load
    self._load_from_fields(entry, self.FIELDS)
  File "/home/x/hsoft/moneyguru/core/gui/table.py", line 673, in _load_from_fields
    setattr(self, row_attr, getattr(target, target_attr))
ValueError: year 4458994 is out of range

**Comment by rp42** [comment]
I'm seeing a similar error when reconciling scheduled transactions on a savings account. See traceback below. I've tried a few times now, and it seems to crash when I reconcile a scheduled transaction, a non-scheduled one seemed OK.

`
Application Name: moneyGuru
Version: 3.0.1

Traceback (most recent call last):
  File "/usr/local/lib/moneyguru/qt/controller/main_window.py", line 586, in reconcileSelectedTriggered
    self._activeView().etable.toggle_reconciled()
  File "/usr/local/lib/moneyguru/core/gui/entry_table.py", line 137, in toggle_reconciled
    self.mainwindow.revalidate()
  File "/usr/local/lib/moneyguru/core/gui/base.py", line 200, in revalidate
    self._revalidate()
  File "/usr/local/lib/moneyguru/core/gui/main_window.py", line 309, in _revalidate
    self._current_pane.view.revalidate()
  File "/usr/local/lib/moneyguru/core/gui/base.py", line 200, in revalidate
    self._revalidate()
  File "/usr/local/lib/moneyguru/core/gui/account_view.py", line 46, in _revalidate
    TransactionViewBase._revalidate(self)
  File "/usr/local/lib/moneyguru/core/gui/transaction_view.py", line 45, in _revalidate
    self.table.refresh_and_show_selection()
  File "/usr/local/lib/moneyguru/core/gui/table.py", line 585, in refresh_and_show_selection
    self.refresh(refresh_view=False)
  File "/usr/local/lib/moneyguru/core/gui/table.py", line 393, in refresh
    self._fill()
  File "/usr/local/lib/moneyguru/core/gui/entry_table.py", line 77, in _fill
    rows = self._get_account_rows(account)
  File "/usr/local/lib/moneyguru/core/gui/entry_table_base.py", line 389, in _get_account_rows
    row = self.ENTRY_ROWCLASS(self, entry, account)
  File "/usr/local/lib/moneyguru/core/gui/entry_table_base.py", line 149, in __init__
    self.load()
  File "/usr/local/lib/moneyguru/core/gui/entry_table_base.py", line 197, in load
    self._load_from_fields(entry, self.FIELDS)
  File "/usr/local/lib/moneyguru/core/gui/table.py", line 673, in _load_from_fields
    setattr(self, row_attr, getattr(target, target_attr))
ValueError: year 4458091 is out of range
`

**Comment by hsoft** [comment]
Sorry, moneyGuru is now unmaintained. See https://github.com/hsoft/moneyguru#unmaintained
